### PR TITLE
Added Merkle Sum Tree Chip

### PR DESCRIPTION
**Pull request by enricobottazzi**

### CODE REVIEW

**Comment by sifnoc** [comment]
I had some tests with the Merkle sum tree, and everything worked perfectly as expected. I have a subject about the Merkle sum tree implementation.<br> for generating a hash, there is an array of indexes for swapping between two nodes(or leaves). 
https://github.com/summa-dev/halo2-experiments/blob/6986429861b2d9abc1357ebe10189b782a9f53f0/src/chips/merkle_sum_tree.rs#L218-L223
That is very intuitive and easy to understand for me. In our first target(1 million rows), we need a maximum of ~20 elements in the indices array for generating each proof. I think it's fairly enough, but we can try to use a 'leaf index' instead of.

This tree implementation seems like a binary tree, If there is an odd number of users, we can generate the hash with empty data for the last of elements in leaves. but it may look like using an imitation account.
So we can inform the user that the data leaf is next to the one with the empty sibling.

**Comment by enricobottazzi** [comment]
Thanks for the review! What do you mean by `leaf index`? Can you explain more about that?

Regarding the second point. You are right about the tree structure and the need for adding empty leaves to fill up the difference between the number of users and the required entries in the tree. This feature will be handled at merkle sum tree generation by the [Merkle Sum Tree Rust Library](https://github.com/summa-dev/merkle-sum-tree-rust). 

> So we can inform the user that the data leaf is next to the one with the empty sibling.

Is this suggestion related to any "business" issue or security issue?

**Comment by sifnoc** [comment]
> Thanks for the review! What do you mean by `leaf index`? Can you explain more about that?
> 
        root
        /   \
      h(0)  h(1)
      / \    / \
    L0  L1 L2  L3
I mean the number on the name of the leaves. 
but I now think it might make the circuit more complicated to regenerate indices using only a single number.
 
> Is this suggestion related to any "business" issue or security issue?

I thought that we should inform the user, because I imagined the data from the sibling must have a 0 value.

**Review by sifnoc — APPROVED** [review]
Great! we can wrap up these experimental components

**Pull request merged**
